import { describe, it, expect } from "vitest";
import {
  isSingboxProfile,
  parseSingboxProfile,
  outboundToNode,
} from "../singboxProfile";

const PROFILE = {
  _comment: "Generated by Surge Config Center",
  log: { level: "info" },
  inbounds: [{ type: "tun", tag: "tun-in", auto_route: true }],
  outbounds: [
    { type: "selector", tag: "🚀 节点选择", outbounds: ["US-vless", "JP-ss"] },
    {
      type: "vless",
      tag: "US-Reality",
      server: "1.2.3.4",
      server_port: 443,
      uuid: "u-1",
      flow: "xtls-rprx-vision",
      tls: {
        enabled: true,
        server_name: "www.microsoft.com",
        utls: { enabled: true, fingerprint: "chrome" },
        reality: { enabled: true, public_key: "PBK", short_id: "SID" },
      },
    },
    {
      type: "vless",
      tag: "US-WS",
      server: "cdn.example.com",
      server_port: 443,
      uuid: "u-2",
      tls: { enabled: true, server_name: "cdn.example.com", insecure: true },
      transport: { type: "ws", path: "/ws", headers: { Host: "cdn.example.com" } },
    },
    {
      type: "shadowsocks",
      tag: "JP-ss",
      server: "jp.example.net",
      server_port: 8388,
      method: "aes-256-gcm",
      password: "pw",
    },
    {
      type: "shadowsocksr",
      tag: "HK-ssr",
      server: "hk.example.org",
      server_port: 443,
      method: "aes-256-cfb",
      password: "pw2",
      protocol: "auth_aes128_md5",
      protocol_param: "32:ab",
      obfs: "http_simple",
      obfs_param: "win.example.com",
    },
    { type: "direct", tag: "direct" },
    { type: "block", tag: "block" },
  ],
  route: { rules: [{ action: "route", outbound: "direct", domain_suffix: ["cn"] }] },
};

describe("isSingboxProfile", () => {
  it("识别带 outbounds 的 JSON 为 profile", () => {
    expect(isSingboxProfile(JSON.stringify(PROFILE))).toBe(true);
  });
  it("分享链接列表不是 profile", () => {
    expect(isSingboxProfile("vless://x@a:1\nss://y@b:2")).toBe(false);
  });
  it("非法 JSON 不是 profile", () => {
    expect(isSingboxProfile("{ not json")).toBe(false);
  });
  it("没有 outbounds 的 JSON 不是 profile", () => {
    expect(isSingboxProfile('{"log":{}}')).toBe(false);
  });
});

describe("parseSingboxProfile", () => {
  it("只抽真实节点,跳过 selector/direct/block", () => {
    const { nodes, errors } = parseSingboxProfile(JSON.stringify(PROFILE));
    expect(errors).toHaveLength(0);
    expect(nodes.map((n) => n.protocol)).toEqual([
      "vless",
      "vless",
      "shadowsocks",
      "shadowsocksr",
    ]);
    expect(nodes.map((n) => n.name)).toEqual([
      "US-Reality",
      "US-WS",
      "JP-ss",
      "HK-ssr",
    ]);
  });

  it("vless + reality 字段完整还原", () => {
    const n = parseSingboxProfile(JSON.stringify(PROFILE)).nodes[0];
    expect(n).toMatchObject({
      protocol: "vless",
      server: "1.2.3.4",
      port: 443,
      uuid: "u-1",
      flow: "xtls-rprx-vision",
      security: "reality",
      sni: "www.microsoft.com",
      publicKey: "PBK",
      shortId: "SID",
      fingerprint: "chrome",
      network: "tcp",
    });
  });

  it("vless + ws + tls(insecure)还原传输层", () => {
    const n = parseSingboxProfile(JSON.stringify(PROFILE)).nodes[1];
    expect(n).toMatchObject({
      network: "ws",
      security: "tls",
      path: "/ws",
      host: "cdn.example.com",
      insecure: true,
    });
  });

  it("shadowsocksr 参数完整", () => {
    const n = parseSingboxProfile(JSON.stringify(PROFILE)).nodes[3];
    expect(n).toMatchObject({
      protocol: "shadowsocksr",
      ssrProtocol: "auth_aes128_md5",
      protocolParam: "32:ab",
      obfs: "http_simple",
      obfsParam: "win.example.com",
    });
  });

  it("同一节点重复出现按 id 去重", () => {
    const dup = { outbounds: [PROFILE.outbounds[3], PROFILE.outbounds[3]] };
    expect(parseSingboxProfile(JSON.stringify(dup)).nodes).toHaveLength(1);
  });

  it("坏节点(缺字段)跳过并记录,不影响其他", () => {
    const mixed = {
      outbounds: [
        { type: "shadowsocks", tag: "bad", server: "x" }, // 缺 port/method
        PROFILE.outbounds[4], // 好的 ss
      ],
    };
    const { nodes, errors } = parseSingboxProfile(JSON.stringify(mixed));
    expect(nodes).toHaveLength(1);
    expect(errors).toHaveLength(1);
  });
});

describe("outboundToNode", () => {
  it("非节点类型直接报错", () => {
    expect(() => outboundToNode({ type: "selector", tag: "g" })).toThrow();
  });
});
